package com.IsmailMabrouki.Transpoz.client;


import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "client")
public class Client {
    @Id
    private Long id; // Unique identifier (often auto-generated by the database)

    private String name; // Customer name

    private String email; // Customer email address (should be unique)

    private String phoneNumber; // Optional: Customer phone number

    @OneToOne(cascade = CascadeType.ALL)
    private Address address; // Optional: Customer's default address

        // Getters and Setters (omitted for brevity)

//        // Optional: Add a constructor to initialize user object
//        public Client(String name, String email, String phoneNumber, Address address) {
//            this.name = name;
//            this.email = email;
//            this.phoneNumber = phoneNumber;
//            this.address = address;
//        }

        // Optional: Add methods specific to users (e.g., password management if applicable)
    }

